# Generated by Django 4.0.6 on 2022-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№')),
                ('order_id', models.IntegerField(verbose_name='Заказ №')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Стоимость,$')),
                ('price_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Стоимость,RUB')),
                ('delivery_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Срок поставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['number'],
            },
        ),
    ]
