# Generated by Django 4.0.6 on 2022-07-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal', '0002_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Заказ №'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Стоимость в руб.'),
        ),
    ]
